### ISSUE TITLE
Prevent Test::More to be loaded more safely?

### ISSUE THREAD

**Issue by miyagawa** [miyagawa/forkprove#4]
If you add Test::More, or a module that eventually loads Test::More to the preloaded modules, things will end up pretty badly.

Maybe we could install a `@INC` hook in forkprove to prevent loading them in the parent process for the extra safety?

**Comment by wolfsage** [comment]
Interesting. We've been using forkprove with -MSome::Module where Some::Module loads Test::More and things have been behaving fine *until* upgrading to latest Test::Simple which includes all of Exodist's Test2 work: https://github.com/Test-More/test-more/issues/659

**Comment by exodist** [comment]
https://github.com/miyagawa/forkprove/pull/13
and
https://github.com/Test-More/test-more/pull/672
